/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cmilkshake;

import cmilkshake.ass.Ass;
import cmilkshake.status.CompareTextReport;
import cmilkshake.status.Counter;
import cmilkshake.table.AssTableModel;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.File;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 *
 * @author util2
 */
public class MainFrame extends javax.swing.JFrame {

    private AssTableModel tableModel_A,  tableModel_B;
    private List<Ass> ass_list = new ArrayList<>();
    private CompareTextReport textReport = null;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        init();
    }
    
    private void init(){
        // Size 1824x1026
        setSize(1824, 1026);
        
        // Center
        setLocationRelativeTo(null);
        
        // L&F
        try {
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (UnsupportedLookAndFeelException ex) {
            //Do nothing
        }
        
        // Icon
        URL url = getClass().getResource("caramel.png");
        java.awt.Toolkit kit = java.awt.Toolkit.getDefaultToolkit();
        java.awt.Image img = kit.createImage(url);
        setIconImage(img);
        
        splitASS.setDividerLocation(0.5d);
        
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                splitASS.setDividerLocation(0.5d);
            }
        });
    }
    
    private void reinitTable(Ass ass_A, Ass ass_B){
        if(ass_A != null){
            // Table A (origin)
            tableModel_A = new AssTableModel(assTable_A);
            assTable_A.setModel(tableModel_A);
            tableModel_A.add(ass_A);
            tableModel_A.updateColumnSize(assTable_A);
        }
        
        if(ass_B != null){
            // Table B (another)
            tableModel_B = new AssTableModel(assTable_B);
            assTable_B.setModel(tableModel_B);
            tableModel_B.add(ass_B);
            tableModel_B.updateColumnSize(assTable_B);
        }
        
        if(ass_A != null && ass_B != null){
            textReport = Counter.compareText(ass_A, ass_B);
            tableModel_A.applyTextReport(textReport);
            tableModel_B.applyTextReport(textReport);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnQuit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnNewDoc = new javax.swing.JButton();
        btnOpenDoc = new javax.swing.JButton();
        btnSaveDoc = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        splitASS = new javax.swing.JSplitPane();
        sp_B = new javax.swing.JScrollPane();
        assTable_B = new javax.swing.JTable();
        sp_A = new javax.swing.JScrollPane();
        assTable_A = new javax.swing.JTable();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caramel Milkshake :: Hey boy, a milkshake please ! v2.3 - GraalVM");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnQuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cmilkshake/images/48px-Crystal_Clear_action_exit.png"))); // NOI18N
        btnQuit.setText("Quit");
        btnQuit.setFocusable(false);
        btnQuit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnQuit);
        jToolBar1.add(jSeparator1);

        btnNewDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cmilkshake/images/48_newdocument.png"))); // NOI18N
        btnNewDoc.setText("New");
        btnNewDoc.setFocusable(false);
        btnNewDoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewDoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewDocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNewDoc);

        btnOpenDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cmilkshake/images/48_folder.png"))); // NOI18N
        btnOpenDoc.setText("Open");
        btnOpenDoc.setFocusable(false);
        btnOpenDoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenDoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOpenDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenDocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnOpenDoc);

        btnSaveDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cmilkshake/images/48_floppydisk.png"))); // NOI18N
        btnSaveDoc.setText("Save");
        btnSaveDoc.setFocusable(false);
        btnSaveDoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSaveDoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSaveDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDocActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSaveDoc);
        jToolBar1.add(jSeparator2);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cmilkshake/images/48px-Crystal_Clear_action_back.png"))); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cmilkshake/images/48px-Crystal_Clear_action_forward.png"))); // NOI18N

        sp_B.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        assTable_B.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        sp_B.setViewportView(assTable_B);

        splitASS.setRightComponent(sp_B);

        sp_A.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        assTable_A.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        sp_A.setViewportView(assTable_A);

        splitASS.setLeftComponent(sp_A);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitASS, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitASS, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Two ASS Comparison", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab1", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jTabbedPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnNewDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewDocActionPerformed

    private void btnOpenDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenDocActionPerformed
        JFileChooser fc = new JFileChooser();
        for(javax.swing.filechooser.FileFilter ff : fc.getChoosableFileFilters()){
            fc.removeChoosableFileFilter(ff);
        }
        fc.addChoosableFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File file) {
                return file.isDirectory() | file.getName().endsWith(".ass");
            }

            @Override
            public String getDescription() {
                return "ASS files";
            }
        });
        fc.setMultiSelectionEnabled(true);        
        int z = fc.showOpenDialog(this);        
        if(z == JFileChooser.APPROVE_OPTION){
            File[] files = fc.getSelectedFiles();
            Arrays.sort(files, Comparator.comparingLong(File::lastModified));
            for(File file : files){                
                ass_list.add(Ass.read(file.getPath()));
            }
            if(ass_list.isEmpty() == false){
                if(ass_list.size() >= 2){                    
                    reinitTable(ass_list.get(0), ass_list.get(1));
                    assTable_A.revalidate(); assTable_B.revalidate();
                    assTable_A.updateUI(); assTable_B.updateUI();
                }else{
                    reinitTable(ass_list.get(0), null);
                    
                    assTable_A.revalidate();
                    assTable_A.updateUI();
                }
            }
        }
    }//GEN-LAST:event_btnOpenDocActionPerformed

    private void btnSaveDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveDocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable assTable_A;
    private javax.swing.JTable assTable_B;
    private javax.swing.JButton btnNewDoc;
    private javax.swing.JButton btnOpenDoc;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnSaveDoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JScrollPane sp_A;
    private javax.swing.JScrollPane sp_B;
    private javax.swing.JSplitPane splitASS;
    // End of variables declaration//GEN-END:variables
}
